/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekpemdas2;

import java.sql.PreparedStatement;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;

import java.util.*;

import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;

/**
 *
 * @author Win10MC
 */
public class dataBuku extends javax.swing.JFrame {
    
    private static final String username = "root";
    private static final String password = "26072003";
    private static final String dtcon = "jdbc:mysql://localhost:3308/perpustakaan";

    Connection sqlconn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;

    /**
     * Creates new form dataBuku
     */
    public dataBuku() {
        initComponents();
        UpdateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fno = new javax.swing.JTextField();
        fpenerbit = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        fkategori = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBuku = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fpengarang = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        fkode = new javax.swing.JTextField();
        Tahun = new javax.swing.JLabel();
        ftahun = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fjudul = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSimpan1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("DATA BUKU PERPUSTAKAAN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 10, -1, -1));

        jPanel2.setLayout(null);
        jPanel2.add(fno);
        fno.setBounds(350, 420, 188, 22);

        fpenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpenerbitActionPerformed(evt);
            }
        });
        jPanel2.add(fpenerbit);
        fpenerbit.setBounds(350, 180, 188, 22);

        btnSimpan.setBackground(new java.awt.Color(255, 136, 118));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);
        btnSimpan.setBounds(140, 540, 140, 40);

        jLabel4.setText("Kategori               :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(180, 240, 148, 16);

        btnUbah.setBackground(new java.awt.Color(0, 181, 191));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setBorder(null);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel2.add(btnUbah);
        btnUbah.setBounds(330, 540, 150, 40);

        fkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fkategoriActionPerformed(evt);
            }
        });
        jPanel2.add(fkategori);
        fkategori.setBounds(350, 240, 188, 22);

        tabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Eksemplar", "Judul", "Penerbit", "Kategori", "Pengarang", "Tahun", "no rak"
            }
        ));
        tabelBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBuku);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(640, 170, 460, 280);

        jLabel5.setText("Pengarang           :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(180, 300, 93, 16);

        jLabel1.setText("Kode Eksemplar  : ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 60, 96, 16);
        jPanel2.add(fpengarang);
        fpengarang.setBounds(350, 300, 188, 22);

        btnBatal.setBackground(new java.awt.Color(255, 209, 126));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBatal.setText("Hapus");
        btnBatal.setBorder(null);
        btnBatal.setBorderPainted(false);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel2.add(btnBatal);
        btnBatal.setBounds(530, 540, 140, 40);
        jPanel2.add(fkode);
        fkode.setBounds(350, 60, 188, 22);

        Tahun.setText("Tahun                  :");
        jPanel2.add(Tahun);
        Tahun.setBounds(180, 360, 90, 16);

        ftahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftahunActionPerformed(evt);
            }
        });
        jPanel2.add(ftahun);
        ftahun.setBounds(350, 360, 188, 22);

        jLabel2.setText("Judul                   :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(180, 120, 88, 16);

        fjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fjudulActionPerformed(evt);
            }
        });
        jPanel2.add(fjudul);
        fjudul.setBounds(350, 120, 188, 22);

        jLabel7.setText("no rak                  :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(180, 420, 90, 16);

        btnKembali.setBackground(new java.awt.Color(228, 138, 248));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setBorder(null);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel2.add(btnKembali);
        btnKembali.setBounds(920, 530, 130, 50);

        btnHapus.setBackground(new java.awt.Color(0, 208, 164));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHapus.setText("Batal");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnHapus);
        btnHapus.setBounds(730, 530, 130, 50);

        jLabel3.setText("Penerbit               :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(180, 180, 148, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel8.setText("Data Buku Perpustakaan");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(680, 110, 250, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekpemdas2/img/CRUD-01.jpg"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, -60, 1160, 680);

        btnSimpan1.setBackground(new java.awt.Color(255, 136, 118));
        btnSimpan1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSimpan1.setText("Simpan");
        btnSimpan1.setBorder(null);
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan1);
        btnSimpan1.setBounds(150, 550, 120, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fpenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fpenerbitActionPerformed

    private void fkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fkategoriActionPerformed

    private void ftahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftahunActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlconn = DriverManager.getConnection(dtcon,username,password);
            pst = sqlconn.prepareStatement("update buku set judul = ?, penerbit = ?, kategori=?, pengarang= ?, tahun = ?, no_rak = ? where kode_eksemplar = ?");
            
            DefaultTableModel RecordTable = (DefaultTableModel)tabelBuku.getModel();
            int SelectedRows = tabelBuku.getSelectedRow();
        
            int newId = (int) RecordTable.getValueAt(SelectedRows, 0);
            
            pst.setString(1,fjudul.getText());
            pst.setString(2,fpenerbit.getText());
            pst.setString(3,fkategori.getText());
            pst.setString(4,fpengarang.getText());
            pst.setString(5,ftahun.getText());            
            pst.setString(6,fno.getText());
            pst.setString(7,fkode.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil diubah");
            UpdateDB();       
        }        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
            fkode.setText(" ");
            fjudul.setText(" ");
            fpenerbit.setText(" ");
            fkategori.setText(" ");
            fpengarang.setText(" ");
            ftahun.setText(" ");
            fno.setText(" ");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tabelBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBukuMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)tabelBuku.getModel();
        int SelectedRows = tabelBuku.getSelectedRow();
        
        fkode.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        fjudul.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        fpenerbit.setText(RecordTable.getValueAt(SelectedRows,2).toString());
        fkategori.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        fpengarang.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        ftahun.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        fno.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
    }//GEN-LAST:event_tabelBukuMouseClicked

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        Mainframe jfrm3= new Mainframe();
        jfrm3.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void fjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fjudulActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
//        try{
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            sqlconn = DriverManager.getConnection(dtcon,username,password);
//            pst = sqlconn.prepareStatement("insert into mahasiswa(nim,nama,email,fakultas,program_studi)value(?,?,?,?,?)");
//
//            pst.setString(1,fnama.getText());
//            pst.setString(2,fnim.getText());
//            pst.setString(3,femail.getText());
//            pst.setString(4,ffakultas.getText());
//            pst.setString(5,fprodi.getText());
//
//            pst.executeUpdate();
//            JOptionPane.showMessageDialog(this, "Data Berhasil ditambahkan");
//            UpdateDB();
//
//            fnama.setText(" ");
//            fnim.setText(" ");
//            femail.setText(" ");
//            ffakultas.setText(" ");
//            fprodi.setText(" ");
//        }
//        catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (SQLException ex) {
//            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlconn = DriverManager.getConnection(dtcon,username,password);
            pst = sqlconn.prepareStatement("insert into buku(kode_eksemplar,judul,penerbit,kategori,pengarang,tahun,no_rak)value(?,?,?,?,?,?,?)");

            pst.setString(1,fkode.getText());
            pst.setString(2,fjudul.getText());
            pst.setString(3,fpenerbit.getText());
            pst.setString(4,fkategori.getText());
            pst.setString(5,fpengarang.getText());
            pst.setString(6,ftahun.getText());
            pst.setString(7,fno.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil ditambahkan");
            UpdateDB();

            fkode.setText(" ");
            fjudul.setText(" ");
            fpenerbit.setText(" ");
            fkategori.setText(" ");
            fpengarang.setText(" ");
            ftahun.setText(" ");
            fno.setText(" ");
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    public void UpdateDB(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlconn = DriverManager.getConnection(dtcon,username,password);
            pst = sqlconn.prepareStatement("select * from buku");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)tabelBuku.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for (i = 1; i <= q; i++){
                    columnData.add(rs.getInt("kode_eksemplar"));
                    columnData.add(rs.getString("judul"));
                    columnData.add(rs.getString("penerbit"));
                    columnData.add(rs.getString("kategori"));
                    columnData.add(rs.getString("pengarang"));
                    columnData.add(rs.getInt("tahun"));
                    columnData.add(rs.getInt("no_rak"));
                }
                RecordTable.addRow(columnData);
            }
            
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tahun;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField fjudul;
    private javax.swing.JTextField fkategori;
    private javax.swing.JTextField fkode;
    private javax.swing.JTextField fno;
    private javax.swing.JTextField fpenerbit;
    private javax.swing.JTextField fpengarang;
    private javax.swing.JTextField ftahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBuku;
    // End of variables declaration//GEN-END:variables
}
