/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekpemdas2;

import java.sql.PreparedStatement;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;

import java.util.*;

import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;

/**
 *
 * @author Win10MC
 */
public class dataMahasiswa extends javax.swing.JFrame {
    private static final String username = "root";
    private static final String password = "26072003";
    private static final String dtcon = "jdbc:mysql://localhost:3308/perpustakaan";

    Connection sqlconn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    
    /**
     * Creates new form dataMahasiswa
     */
    public dataMahasiswa() {
        initComponents();
        UpdateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        femail = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        ffakultas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fprodi = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        fnama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fnim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnBatal1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnBatal2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        femail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        femail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femailActionPerformed(evt);
            }
        });
        jPanel2.add(femail);
        femail.setBounds(350, 260, 188, 26);

        btnSimpan.setBackground(new java.awt.Color(255, 136, 118));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);
        btnSimpan.setBounds(150, 560, 120, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Fakultas                :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 340, 130, 20);

        btnUbah.setBackground(new java.awt.Color(0, 181, 191));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setBorder(null);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel2.add(btnUbah);
        btnUbah.setBounds(339, 560, 130, 40);

        ffakultas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ffakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffakultasActionPerformed(evt);
            }
        });
        jPanel2.add(ffakultas);
        ffakultas.setBounds(350, 340, 188, 26);

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "NIM", "Email", "Fakultas", "Program Studi"
            }
        ));
        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMahasiswa);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(640, 190, 460, 290);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Program Studi      : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 420, 130, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel1.setText("Data Mahasiswa");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(720, 140, 210, 25);

        fprodi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fprodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fprodiActionPerformed(evt);
            }
        });
        jPanel2.add(fprodi);
        fprodi.setBounds(350, 420, 188, 26);

        btnBatal.setBackground(new java.awt.Color(255, 209, 126));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setBorder(null);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel2.add(btnBatal);
        btnBatal.setBounds(540, 560, 130, 40);

        fnama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(fnama);
        fnama.setBounds(350, 100, 188, 26);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("NIM                      :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 180, 120, 20);

        fnim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(fnim);
        fnim.setBounds(350, 180, 188, 26);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Email                     :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 260, 120, 20);

        btnKembali.setBackground(new java.awt.Color(228, 138, 248));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setBorder(null);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel2.add(btnKembali);
        btnKembali.setBounds(920, 550, 130, 50);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nama                    :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(170, 100, 120, 20);

        btnBatal1.setBackground(new java.awt.Color(0, 208, 164));
        btnBatal1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnBatal1.setText("Hapus");
        btnBatal1.setBorder(null);
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBatal1);
        btnBatal1.setBounds(720, 560, 140, 40);

        jLabel8.setBackground(new java.awt.Color(255, 129, 129));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekpemdas2/img/CRUD-01.jpg"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, -30, 1150, 660);

        btnBatal2.setText("Batal");
        btnBatal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBatal2);
        btnBatal2.setBounds(535, 112, 109, 22);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("DATA MAHASISWA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(541, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(440, 440, 440))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femailActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlconn = DriverManager.getConnection(dtcon,username,password);
            pst = sqlconn.prepareStatement("insert into mahasiswa(nim,nama,email,fakultas,program_studi)value(?,?,?,?,?)");

            pst.setString(1,fnama.getText());
            pst.setString(2,fnim.getText());
            pst.setString(3,femail.getText());
            pst.setString(4,ffakultas.getText());
            pst.setString(5,fprodi.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil ditambahkan");
            UpdateDB();

            fnama.setText(" ");
            fnim.setText(" ");
            femail.setText(" ");
            ffakultas.setText(" ");
            fprodi.setText(" ");
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlconn = DriverManager.getConnection(dtcon,username,password);
            pst = sqlconn.prepareStatement("update mahasiswa set nama = ?, email = ?, fakultas=?, program_studi= ? where nim = ?");

            pst.setString(1,fnama.getText());
            pst.setString(2,femail.getText());
            pst.setString(3,ffakultas.getText());
            pst.setString(4,fprodi.getText());
            pst.setString(5,fnim.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil diubah");
            UpdateDB();
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void ffakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffakultasActionPerformed

    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMahasiswaMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)tabelMahasiswa.getModel();
        int SelectedRows = tabelMahasiswa.getSelectedRow();

        fnama.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        fnim.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        femail.setText(RecordTable.getValueAt(SelectedRows,2).toString());
        ffakultas.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        fprodi.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
    }//GEN-LAST:event_tabelMahasiswaMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        fnama.setText(" ");
        fnim.setText(" ");
        femail.setText(" ");
        ffakultas.setText(" ");
        fprodi.setText(" ");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        Mainframe jfrm3= new Mainframe();
        jfrm3.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose(); 
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnBatal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatal2ActionPerformed

    private void fprodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fprodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fprodiActionPerformed

    public void UpdateDB(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlconn = DriverManager.getConnection(dtcon,username,password);
            pst = sqlconn.prepareStatement("select * from mahasiswa");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)tabelMahasiswa.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for (i = 1; i <= q; i++){
                    columnData.add(rs.getString("nama"));
                    columnData.add(rs.getString("nim"));
                    columnData.add(rs.getString("email"));
                    columnData.add(rs.getString("fakultas"));
                    columnData.add(rs.getString("program_studi"));
                }
                RecordTable.addRow(columnData);
            }
            
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnBatal2;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField femail;
    private javax.swing.JTextField ffakultas;
    private javax.swing.JTextField fnama;
    private javax.swing.JTextField fnim;
    private javax.swing.JTextField fprodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMahasiswa;
    // End of variables declaration//GEN-END:variables
}
