/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekpemdas2;

import java.sql.PreparedStatement;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;

import java.util.*;

import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
/**
 *
 * @author Win10MC
 */
public class peminjaman extends javax.swing.JFrame {
    private static final String username = "root";
    private static final String password = "26072003";
    private static final String dtcon = "jdbc:mysql://localhost:3308/perpustakaan";

    Connection sqlconn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;

    /**
     * Creates new form peminjaman
     */
    public peminjaman() {
        initComponents();
        UpdateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        fnim = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        ftglpinjam = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeminjaman = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ftglkembali = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        fpinjam = new javax.swing.JTextField();
        Tahun = new javax.swing.JLabel();
        fpetugas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fdetail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnKembali1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        fnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnimActionPerformed(evt);
            }
        });
        jPanel2.add(fnim);
        fnim.setBounds(350, 210, 188, 22);

        btnSimpan.setBackground(new java.awt.Color(255, 136, 118));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan);
        btnSimpan.setBounds(150, 530, 120, 50);

        jLabel4.setText("Tanggal Pinjam    :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(180, 270, 160, 16);

        btnUbah.setBackground(new java.awt.Color(0, 181, 191));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.setBorder(null);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel2.add(btnUbah);
        btnUbah.setBounds(340, 530, 130, 50);

        ftglpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftglpinjamActionPerformed(evt);
            }
        });
        jPanel2.add(ftglpinjam);
        ftglpinjam.setBounds(350, 270, 188, 22);

        tabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pinjam", "ID Detail", "Nim", "Tanggal Pinjam", "Tanggal Kembali", "ID Petugas"
            }
        ));
        tabelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPeminjaman);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(640, 180, 460, 270);

        jLabel5.setText("Tanggal Kembali  :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(180, 330, 97, 16);

        jLabel1.setText("ID Pinjam           :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 90, 136, 16);
        jPanel2.add(ftglkembali);
        ftglkembali.setBounds(350, 330, 190, 22);

        btnBatal.setBackground(new java.awt.Color(255, 209, 126));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.setBorder(null);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel2.add(btnBatal);
        btnBatal.setBounds(539, 530, 130, 50);
        jPanel2.add(fpinjam);
        fpinjam.setBounds(350, 90, 188, 22);

        Tahun.setText("ID Petugas           :");
        jPanel2.add(Tahun);
        Tahun.setBounds(180, 390, 92, 16);

        fpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpetugasActionPerformed(evt);
            }
        });
        jPanel2.add(fpetugas);
        fpetugas.setBounds(350, 390, 190, 22);

        jLabel2.setText("Nama                 :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(180, 150, 86, 16);

        fdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdetailActionPerformed(evt);
            }
        });
        jPanel2.add(fdetail);
        fdetail.setBounds(350, 150, 188, 22);

        jLabel3.setText("Nim                    :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(180, 210, 138, 16);

        btnKembali.setBackground(new java.awt.Color(228, 138, 248));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setBorder(null);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jPanel2.add(btnKembali);
        btnKembali.setBounds(919, 522, 130, 50);

        btnKembali1.setBackground(new java.awt.Color(0, 208, 164));
        btnKembali1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKembali1.setText("Hapus");
        btnKembali1.setBorder(null);
        btnKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembali1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnKembali1);
        btnKembali1.setBounds(720, 530, 140, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        jLabel7.setText("Data Peminjaman");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(710, 110, 200, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekpemdas2/img/CRUD-01.jpg"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, -80, 1140, 710);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("DATA PEMINJAMAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(507, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(456, 456, 456))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnimActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlconn = DriverManager.getConnection(dtcon,username,password);
            pst = sqlconn.prepareStatement("insert into peminjaman(id_pinjam,id_detail,nim,tgl_pinjam,tgl_kembali,id_petugas)value(?,?,?,?,?,?)");

            pst.setString(1,fpinjam.getText());
            pst.setString(2,fdetail.getText());
            pst.setString(3,fnim.getText());
            pst.setString(4,ftglpinjam.getText());
            pst.setString(5,ftglkembali.getText());
            pst.setString(6,fpetugas.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil ditambahkan");
            UpdateDB();

            fpinjam.setText(" ");
            fdetail.setText(" ");
            fnim.setText(" ");
            ftglpinjam.setText(" ");
            ftglkembali.setText(" ");
            fpetugas.setText(" ");
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlconn = DriverManager.getConnection(dtcon,username,password);
            pst = sqlconn.prepareStatement("update peminjaman set nim = ?, tgl_pinjam = ?, tgl_kembali=?, id_petugas= ? where id_pinjam = ?");

            pst.setString(1,fnim.getText());
            pst.setString(2,ftglpinjam.getText());
            pst.setString(3,ftglkembali.getText());
            pst.setString(4,fpetugas.getText());
            pst.setString(5, fpinjam.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil diubah");
            UpdateDB();
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void ftglpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftglpinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftglpinjamActionPerformed

    private void tabelPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjamanMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)tabelPeminjaman.getModel();
        int SelectedRows = tabelPeminjaman.getSelectedRow();

        fpinjam.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        fdetail.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        fnim.setText(RecordTable.getValueAt(SelectedRows,2).toString());
        ftglpinjam.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        ftglkembali.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        fpetugas.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
    }//GEN-LAST:event_tabelPeminjamanMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        fpinjam.setText(" ");
        fdetail.setText(" ");
        fnim.setText(" ");
        ftglpinjam.setText(" ");
        ftglkembali.setText(" ");
        fpetugas.setText(" ");
    }//GEN-LAST:event_btnBatalActionPerformed

    private void fpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fpetugasActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        Mainframe jfrm3= new Mainframe();
        jfrm3.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void fdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fdetailActionPerformed

    private void btnKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembali1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembali1ActionPerformed

        public void UpdateDB(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlconn = DriverManager.getConnection(dtcon,username,password);
            pst = sqlconn.prepareStatement("select * from peminjaman");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)tabelPeminjaman.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                
                for (i = 1; i <= q; i++){
                    columnData.add(rs.getString("id_pinjam"));
                    columnData.add(rs.getString("id_detail"));
                    columnData.add(rs.getString("nim"));
                    columnData.add(rs.getString("tgl_pinjam"));
                    columnData.add(rs.getString("tgl_kembali"));
                    columnData.add(rs.getString("id_petugas"));
                }
                RecordTable.addRow(columnData);
            }
            
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tahun;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKembali1;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField fdetail;
    private javax.swing.JTextField fnim;
    private javax.swing.JTextField fpetugas;
    private javax.swing.JTextField fpinjam;
    private javax.swing.JTextField ftglkembali;
    private javax.swing.JTextField ftglpinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPeminjaman;
    // End of variables declaration//GEN-END:variables
}
